version: "3"

services:
  api:
    working_dir: /home/usr/app
    container_name: api
    image: maven:3-adoptopenjdk-8
    ports:
      - "8080:8080"
    volumes:
      - "./financas-api:/home/usr/app"
    command: mvn spring-boot:run

  mobile:
    container_name: app
    build: financas-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api